// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjNAhR4hlNzEdwf4ylOWUuwvpk2P8Cwx0',
    appId: '1:559046730510:web:002ade952b780f94252d5f',
    messagingSenderId: '559046730510',
    projectId: 'tinder-marmiton',
    authDomain: 'tinder-marmiton.firebaseapp.com',
    storageBucket: 'tinder-marmiton.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6pDmBrfGgmPBs4FOaH37nWVTmTksspF4',
    appId: '1:559046730510:android:accca1124a35f287252d5f',
    messagingSenderId: '559046730510',
    projectId: 'tinder-marmiton',
    storageBucket: 'tinder-marmiton.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBCGN4hQdCpwivcq2x03ZcOGttnT_7ltQ',
    appId: '1:559046730510:ios:2d150abff9b19aa7252d5f',
    messagingSenderId: '559046730510',
    projectId: 'tinder-marmiton',
    storageBucket: 'tinder-marmiton.firebasestorage.app',
    iosBundleId: 'com.example.tinderMarmiton',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBCGN4hQdCpwivcq2x03ZcOGttnT_7ltQ',
    appId: '1:559046730510:ios:2d150abff9b19aa7252d5f',
    messagingSenderId: '559046730510',
    projectId: 'tinder-marmiton',
    storageBucket: 'tinder-marmiton.firebasestorage.app',
    iosBundleId: 'com.example.tinderMarmiton',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjNAhR4hlNzEdwf4ylOWUuwvpk2P8Cwx0',
    appId: '1:559046730510:web:2454ac9517694b39252d5f',
    messagingSenderId: '559046730510',
    projectId: 'tinder-marmiton',
    authDomain: 'tinder-marmiton.firebaseapp.com',
    storageBucket: 'tinder-marmiton.firebasestorage.app',
  );
}
